### ISSUE TITLE
dev wallet not started successfully

### ISSUE THREAD

**Issue by kerrywei** [onflow/fcl-dev-wallet#79] opened 2021-12-20 22:37 UTC
## The Issue
dev-wallet is not started succesfully when starting KittyItems project locally, have to call API  http://localhost:8701/api/init to manually revive the dev-wallet

## Definition of Done
ensure dev wallet can be started successfully so that as a contributor, I do not have to manually issue that API request as a workaround

**Comment by 10thfloor** [comment] 2022-01-29 00:42
@alxflw Can you confirm this is still an issue?

**Comment by alxflw** [comment] 2022-01-29 16:09
I cannot reproduce this. I just did a fresh installation of KI and I was able to use the dev wallet (login, init account). I also tried the harness:

<img width="879" alt="Screen Shot 2022-01-29 at 8 06 14 AM" src="https://user-images.githubusercontent.com/97620081/151668104-4dc19ec4-cb0d-4cc7-bc99-f9e824751148.png">

**Comment by 10thfloor** [comment] 2022-02-07 16:41
Fixed in #92 #94

**Closed by 10thfloor** 2022-02-07 16:41 UTC
Labels: Developer Tool Team
